version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:3.6
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  configserver:
    image: alice-projects/configserver:0.0.1-SNAPSHOT
    environment:
      RABBITMQ_HOST: rabbitmq
  eureka:
    image: alice-projects/eureka:0.0.1-SNAPSHOT
  turbine:
    image: alice-projects/turbine:0.0.1-SNAPSHOT
  admin:
    image: alice-projects/admin:0.0.1-SNAPSHOT
    environment:
      ADMIN_PASSWORD: admin
    ports:
      - "9999:9999"
  authserver:
    image: alice-projects/uaa:0.0.1-SNAPSHOT
    environment:
      MYSQL_HOST: mysql
    ports:
      - "9000:9000"
  hello:
    image: alice-projects/hello:0.0.1-SNAPSHOT
    environment:
      RABBITMQ_HOST: rabbitmq
      AUTHSERVER_HOST: authserver
  ui:
    image: alice-projects/ui:0.0.1-SNAPSHOT
    environment:
      RABBITMQ_HOST: rabbitmq
      AUTHSERVER_HOST: authserver
    ports:
      - "8080:8080"